#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    ports:
       - 80:8000
    links:
       - redis:redis
    command: python /code/mysite/manage.py runserver 0.0.0.0:8000

  redis:
    image: redis
    expose:
        - 6379
