# Generated by Django 3.0.4 on 2020-04-30 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('uri', models.URLField()),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=8000)),
                ('has_guides', models.BooleanField()),
                ('has_tutorials', models.BooleanField()),
                ('has_comments', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('md_loc', models.URLField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Resources')),
            ],
        ),
        migrations.CreateModel(
            name='Guides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('md_loc', models.URLField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.Resources')),
            ],
        ),
    ]
