# Generated by Django 3.0.4 on 2020-05-05 21:48

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resources',
            name='descriptionMD',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
    ]
