# Generated by Django 3.0.4 on 2020-05-05 22:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_resources_descriptionmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guides',
            name='md_loc',
        ),
        migrations.RemoveField(
            model_name='tutorials',
            name='md_loc',
        ),
        migrations.AddField(
            model_name='guides',
            name='body',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorials',
            name='body',
            field=markdownx.models.MarkdownxField(default=1),
            preserve_default=False,
        ),
    ]
